### PR TITLE
Relicense the project under Apache 2

### PR DESCRIPTION
**Pull request by BomBardyGamer**
I originally made the decision to license the server and most of the project under the GNU General Public License v3.0 because I saw Velocity make the change, and I agreed with their reasoning for it, in that I wished for this project to always remain open-source.

However, Velocity's main reasoning was the problem with downstream forks not contributing changes back to upstream, which is an issue we do not have. In addition, the GNU General Public License imposes many restrictions on how the source code can be used, and the strict requirements imposed by the license may deter some from contributing or using code from the project entirely. This is a problem, as the number one goal of this project is one of learning, and if others cannot feel as if they can freely use and learn from the code, then this goal is somewhat limited.

Therefore, I have made the decision to relicense the entire project under the Apache License v2.0. This license is far more permissive, and I am confident that it will make others more willing to use and adapt source code from this project. I have considered this option for a while, but it has been difficult due to the use of Velocity code, which is GPL licensed. However, I have discovered that, as there were no changes between the code that was MIT licensed, and the code that is GPL licensed, that I can base my derivative on the MIT licensed code, which allows this to go forward.

Though I have already obtained consent directly from the majority of contributors, I would like for all contributors to explicitly give their permission in a comment in this pull request, to make it explicitly clear that they approve of this change.

### CODE REVIEW

**Comment by knightzmc** [comment]
All fine by me, approval given :D

**Comment by jan-tennert** [comment]
Lgtm 👍

**Comment by aidanjbennett** [comment]
I (Aidan Bennett) give @BomBardyGamer and @KryptonMC permission to use my horrible awful code.

**Comment by tomlister** [comment]
Approval given.

**Pull request merged**
